### ISSUE TITLE
Was anyone able to make this work with Playwright?

### ISSUE THREAD

**Issue by gajus** [mattphillips/jest-chain#41]
Playwright uses Jest behind the scenes, but it is not clear how to make it work with `jest-chain`.

**Comment by mattphillips** [comment]
Hey @gajus 👋

I've taken a look into this for you because you've saved me so much time with slonik - so thanks for that! 

---

You should be able to just wrap Playwright's `expect` with the `chain` function in this library. 

For example:

```js
// expect.js
import { expect as base } from '@playwright/test';
import chain from 'jest-chain/dist/chain';

export const expect = chain(base);
```

Then in your tests you can import `expect` from the above file.

_Note: It might be a nicer DX if I add `chain` to the public API rather than importing from `/dist`._

---

## Typescript support

If you're using Playwright in a Typescript project then the above won't be enough to get the types to play nicely.

Unfortunately Playwright doesn't use the exact same syntax for their matchers as Jest does so it's not as simple to plug the types. I've had a play around though and it should be possible with the following code:

_Note: the following code is a lot of TS machinery to change Playwright's built in matcher return types to be generic to allow chaining. Overall it's largely unimportant to your usage_

<details>
  <summary>Full typescript code</summary>
  
```ts
import { expect as base } from '@playwright/test';
// @ts-ignore
import chain from 'jest-chain/dist/chain';

import { Page, Locator, APIResponse } from '@playwright/test';
import type * as jestExpect from 'expect';

export const expect: Expect = chain(base);

interface Expect {
  <T = unknown>(actual: T, message?: string): ChainedMatchers<T>;
}

type Awaited<T> = T extends PromiseLike<infer U> ? U : T;

type OverriddenExpectProperties =
  | 'not'
  | 'resolves'
  | 'rejects'
  | 'toMatchInlineSnapshot'
  | 'toThrowErrorMatchingInlineSnapshot'
  | 'toMatchSnapshot'
  | 'toThrowErrorMatchingSnapshot';

type MakeReturnGeneric<OriginalType, NewType, Matchers> = {
  [K in keyof Matchers]: Matchers[K] extends (...args: infer Args) => Promise<OriginalType>
    ? (...args: Args) => Promise<NewType> & NewType
    : Matchers[K];
};
type GetPlaywrightMatchersForType<OriginalType, NewType> = MakeReturnGeneric<
  OriginalType,
  NewType,
  Omit<PlaywrightTest.Matchers<OriginalType>['not'], keyof jestExpect.Matchers<OriginalType>>
>;

type PageMatchers<R> = GetPlaywrightMatchersForType<Page, R>;
type LocatorMatchers<R> = GetPlaywrightMatchersForType<Locator, R>;
type APIResponseMatchers<R> = GetPlaywrightMatchersForType<APIResponse, R>;
type DefaultMatchers<R> = Omit<
  PlaywrightTest.Matchers<R>,
  keyof PageMatchers<R> | keyof LocatorMatchers<R> | keyof APIResponseMatchers<R> | OverriddenExpectProperties
>;

type PlaywrightMatchers<R> = DefaultMatchers<R> & PageMatchers<R> & LocatorMatchers<R> & APIResponseMatchers<R>;

interface ChainedMatchers<R> extends Matchers<ChainedMatchers<R>> {}

interface Matchers<R> extends PlaywrightMatchers<R> {
  not: Matchers<R>;
  resolves: Matchers<Awaited<R>>;
  rejects: Matchers<Promise<R>>;
  toMatchSnapshot(options: { name: string | string[]; threshold?: number }): R;
  toMatchSnapshot(
    name: string | string[],
    options?: {
      threshold?: number;
    }
  ): R;
}
``` 
</details>

Here's a screenshot of a test using the above and the editor completions work, types are happy and chained matchers work.

<img width="987" alt="Screenshot 2022-09-28 at 18 19 55" src="https://user-images.githubusercontent.com/5610087/192847751-675b5f1c-5704-4307-a943-a44fa56ed7ea.png">


Let me know if this is good enough for your use case or if you need anymore support 👍

**Comment by gajus** [comment]
This is amazing. Thank you, it worked for our use case.

Def worth adding to the documentation!
